firstNum = input("Please input the first integer value? ")
secondNum = input("Please input the second integer value? ")
print("Processing...")
sum = int(firstNum) + int(secondNum)
sub = int(firstNum) + int(secondNum)
mul = int(firstNum) * int(secondNum)
div = int(firstNum) / int(secondNum)
mod = int(firstNum) % int(secondNum)
print("Addition " + str(sum))
print("Substraction " + str(sub))
print("Multiplication " + str(mul))
print("Division " + str(div))
print("Modulus " + str(mod))